// Do not edit this file.
// You do not need to upload this file.
// Your function in assignment_o_functions.c should match the prototype given
// below.

// Check hasn't already been defined
#ifndef FIND_MAX_LESS_THAN_10
#define FIND_MAX_LESS_THAN_10

// Function prototypes for assignment_o.c
void find_max_less_than_10(const double a[], const int n, double *max);

#endif